#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
#ifndef READYREMITSDK_SWIFT_H
#define READYREMITSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ReadyRemitSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)




enum ReadyRemitApiEnvironment : NSInteger;
@class ReadyRemitAppearance;
@class NSString;
@class UINavigationController;
@protocol ReadyRemitDelegate;

SWIFT_CLASS("_TtC13ReadyRemitSDK10ReadyRemit")
@interface ReadyRemit : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ReadyRemit * _Nonnull shared;)
+ (ReadyRemit * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum ReadyRemitApiEnvironment environment;
@property (nonatomic, strong) ReadyRemitAppearance * _Nonnull appearance;
@property (nonatomic, readonly, copy) NSString * _Nonnull info;
- (void)languageSelected:(NSString * _Nonnull)lang;
- (void)switchFeatureFlags:(NSString * _Nonnull)flag :(BOOL)status;
- (void)launchObjcInNavigation:(UINavigationController * _Nonnull)inNavigation delegate:(id <ReadyRemitDelegate> _Nonnull)delegate onLaunch:(void (^ _Nullable)(void))onLaunch onDismiss:(void (^ _Nullable)(void))onDismiss;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReadyRemit (SWIFT_EXTENSION(ReadyRemitSDK))
@end

@class RequestField;

SWIFT_CLASS("_TtCC13ReadyRemitSDK10ReadyRemit15TransferRequest")
@interface TransferRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull dstCountryIso3Code;
@property (nonatomic, readonly, copy) NSString * _Nonnull dstCurrencyIso3Code;
@property (nonatomic, readonly, copy) NSString * _Nonnull srcCurrencyIso3Code;
@property (nonatomic, readonly, copy) NSString * _Nonnull transferMethod;
@property (nonatomic, readonly, copy) NSString * _Nonnull quoteBy;
@property (nonatomic, readonly) NSInteger amount;
@property (nonatomic, readonly) NSInteger fee;
@property (nonatomic, readonly, copy) NSString * _Nonnull recipientId;
@property (nonatomic, readonly, copy) NSString * _Nullable recipientAccountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull purposeOfRemittance;
@property (nonatomic, readonly, copy) NSArray<RequestField *> * _Nullable fields;
@property (nonatomic, readonly, copy) NSString * _Nullable quoteHistoryId;
- (nonnull instancetype)initWithDstCountryIso3Code:(NSString * _Nonnull)dstCountryIso3Code dstCurrencyIso3Code:(NSString * _Nonnull)dstCurrencyIso3Code srcCurrencyIso3Code:(NSString * _Nonnull)srcCurrencyIso3Code transferMethod:(NSString * _Nonnull)transferMethod quoteBy:(NSString * _Nonnull)quoteBy amount:(NSInteger)amount fee:(NSInteger)fee recipientId:(NSString * _Nonnull)recipientId recipientAccountId:(NSString * _Nullable)recipientAccountId purposeOfRemittance:(NSString * _Nonnull)purposeOfRemittance fields:(NSArray<RequestField *> * _Nullable)fields quoteHistoryId:(NSString * _Nonnull)quoteHistoryId OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)toJSON SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC13ReadyRemitSDK10ReadyRemit12RequestField")
@interface RequestField : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull value;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayText;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name type:(NSString * _Nonnull)type value:(NSString * _Nonnull)value displayText:(NSString * _Nonnull)displayText OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface ReadyRemit (SWIFT_EXTENSION(ReadyRemitSDK))
@end


SWIFT_CLASS("_TtCC13ReadyRemitSDK10ReadyRemit8FontSpec")
@interface FontSpec : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable defaultFamily;)
+ (NSString * _Nullable)defaultFamily SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultFamily:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL dynamicFontsize;)
+ (BOOL)dynamicFontsize SWIFT_WARN_UNUSED_RESULT;
+ (void)setDynamicFontsize:(BOOL)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ReadyRemitApiEnvironment, open) {
  ReadyRemitApiEnvironmentProduction = 0,
  ReadyRemitApiEnvironmentSandbox = 1,
  ReadyRemitApiEnvironmentUat = 2,
};

@class ReadyRemitColorScheme;
@class ReadyRemitFonts;
@class UIColor;
@class UIFont;

SWIFT_CLASS("_TtC13ReadyRemitSDK20ReadyRemitAppearance")
@interface ReadyRemitAppearance : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ReadyRemitAppearance * _Nonnull shared;)
+ (ReadyRemitAppearance * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) ReadyRemitColorScheme * _Nonnull colors;
@property (nonatomic, strong) ReadyRemitFonts * _Nonnull fonts;
- (nonnull instancetype)initWithFonts:(ReadyRemitFonts * _Nonnull)fonts colors:(ReadyRemitColorScheme * _Nonnull)colors OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFonts:(ReadyRemitFonts * _Nonnull)fonts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithColors:(ReadyRemitColorScheme * _Nonnull)colors OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull primaryButtonColor;
@property (nonatomic, strong) UIColor * _Nonnull titleColor;
@property (nonatomic, strong) UIFont * _Nonnull titleFont;
@property (nonatomic, strong) UIFont * _Nonnull pageTitleFont;
@property (nonatomic, strong) UIFont * _Nonnull fieldTitleFont;
@property (nonatomic, strong) UIFont * _Nonnull fieldValueFont;
@property (nonatomic, strong) UIColor * _Nonnull fieldBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull dividerColor;
@property (nonatomic, strong) UIColor * _Nonnull removeColor;
@property (nonatomic, strong) UIColor * _Nonnull buttonColor;
@property (nonatomic, strong) UIColor * _Nonnull disabledColor;
@property (nonatomic, strong) UIFont * _Nonnull disabledFont;
@property (nonatomic, strong) UIColor * _Nonnull highlightedBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull highlightedCapsuleFont;
@property (nonatomic, strong) UIFont * _Nonnull disabledCapsuleFont;
@property (nonatomic, strong) UIColor * _Nonnull currencyDisableColor;
@property (nonatomic, strong) UIFont * _Nonnull currencyDisableFont;
@property (nonatomic, strong) UIColor * _Nonnull transferMoneyColor;
@property (nonatomic, strong) UIFont * _Nonnull transferMoneyFont;
@property (nonatomic, strong) UIFont * _Nonnull navigationFont;
@property (nonatomic, strong) UIFont * _Nonnull navigationCancelFont;
@property (nonatomic, strong) UIColor * _Nonnull navigationColor;
@property (nonatomic, strong) UIColor * _Nonnull navigationCancelColor;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull modalTitleFont;
@property (nonatomic, strong) UIColor * _Nonnull modalTransparentColor;
@property (nonatomic, strong) UIFont * _Nonnull noteFont;
@end


SWIFT_CLASS("_TtC13ReadyRemitSDK21ReadyRemitColorScheme")
@interface ReadyRemitColorScheme : NSObject
@property (nonatomic, strong) UIColor * _Nonnull primaryShade1;
@property (nonatomic, strong) UIColor * _Nonnull primaryShade2;
@property (nonatomic, strong) UIColor * _Nonnull secondaryShade1;
@property (nonatomic, strong) UIColor * _Nonnull secondaryShade2;
@property (nonatomic, strong) UIColor * _Nonnull secondaryShade3;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade1;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade2;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade3;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade4;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade5;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColorPrimary;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColorSecondary;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColorTertiary;
@property (nonatomic, strong) UIColor * _Nonnull error;
@property (nonatomic, strong) UIColor * _Nonnull success;
@property (nonatomic, strong) UIColor * _Nonnull controlShade1;
@property (nonatomic, strong) UIColor * _Nonnull controlShade2;
@property (nonatomic, strong) UIColor * _Nonnull controlAccessoryShade1;
@property (nonatomic, strong) UIColor * _Nonnull controlAccessoryShade2;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryDisabled;
@property (nonatomic, strong) UIColor * _Nonnull textTertiaryDisabled;
@property (nonatomic, strong) UIColor * _Nonnull textQuaternaryDisabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13ReadyRemitSDK18ReadyRemitDelegate_")
@protocol ReadyRemitDelegate
- (void)onAuthTokenRequestWithSuccess:(void (^ _Nonnull)(NSString * _Nonnull))success failure:(void (^ _Nonnull)(void))failure;
- (void)onSubmitTransferWithTransferRequest:(TransferRequest * _Nonnull)transferRequest success:(void (^ _Nonnull)(NSString * _Nonnull))success failure:(void (^ _Nonnull)(NSString * _Nonnull, NSString * _Nonnull))failure;
@optional
- (void)onSDKClose;
@end


SWIFT_CLASS("_TtC13ReadyRemitSDK15ReadyRemitFonts")
@interface ReadyRemitFonts : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ReadyRemitSDK24ReadyRemitObjcOAuthToken")
@interface ReadyRemitObjcOAuthToken : NSObject
- (nonnull instancetype)initWithTokenType:(NSString * _Nonnull)tokenType accessToken:(NSString * _Nonnull)accessToken expiresInSeconds:(NSInteger)expiresInSeconds OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end










#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
#ifndef READYREMITSDK_SWIFT_H
#define READYREMITSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ReadyRemitSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)




enum ReadyRemitApiEnvironment : NSInteger;
@class ReadyRemitAppearance;
@class NSString;
@class UINavigationController;
@protocol ReadyRemitDelegate;

SWIFT_CLASS("_TtC13ReadyRemitSDK10ReadyRemit")
@interface ReadyRemit : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ReadyRemit * _Nonnull shared;)
+ (ReadyRemit * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum ReadyRemitApiEnvironment environment;
@property (nonatomic, strong) ReadyRemitAppearance * _Nonnull appearance;
@property (nonatomic, readonly, copy) NSString * _Nonnull info;
- (void)languageSelected:(NSString * _Nonnull)lang;
- (void)switchFeatureFlags:(NSString * _Nonnull)flag :(BOOL)status;
- (void)launchObjcInNavigation:(UINavigationController * _Nonnull)inNavigation delegate:(id <ReadyRemitDelegate> _Nonnull)delegate onLaunch:(void (^ _Nullable)(void))onLaunch onDismiss:(void (^ _Nullable)(void))onDismiss;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReadyRemit (SWIFT_EXTENSION(ReadyRemitSDK))
@end

@class RequestField;

SWIFT_CLASS("_TtCC13ReadyRemitSDK10ReadyRemit15TransferRequest")
@interface TransferRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull dstCountryIso3Code;
@property (nonatomic, readonly, copy) NSString * _Nonnull dstCurrencyIso3Code;
@property (nonatomic, readonly, copy) NSString * _Nonnull srcCurrencyIso3Code;
@property (nonatomic, readonly, copy) NSString * _Nonnull transferMethod;
@property (nonatomic, readonly, copy) NSString * _Nonnull quoteBy;
@property (nonatomic, readonly) NSInteger amount;
@property (nonatomic, readonly) NSInteger fee;
@property (nonatomic, readonly, copy) NSString * _Nonnull recipientId;
@property (nonatomic, readonly, copy) NSString * _Nullable recipientAccountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull purposeOfRemittance;
@property (nonatomic, readonly, copy) NSArray<RequestField *> * _Nullable fields;
@property (nonatomic, readonly, copy) NSString * _Nullable quoteHistoryId;
- (nonnull instancetype)initWithDstCountryIso3Code:(NSString * _Nonnull)dstCountryIso3Code dstCurrencyIso3Code:(NSString * _Nonnull)dstCurrencyIso3Code srcCurrencyIso3Code:(NSString * _Nonnull)srcCurrencyIso3Code transferMethod:(NSString * _Nonnull)transferMethod quoteBy:(NSString * _Nonnull)quoteBy amount:(NSInteger)amount fee:(NSInteger)fee recipientId:(NSString * _Nonnull)recipientId recipientAccountId:(NSString * _Nullable)recipientAccountId purposeOfRemittance:(NSString * _Nonnull)purposeOfRemittance fields:(NSArray<RequestField *> * _Nullable)fields quoteHistoryId:(NSString * _Nonnull)quoteHistoryId OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)toJSON SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC13ReadyRemitSDK10ReadyRemit12RequestField")
@interface RequestField : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull value;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayText;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name type:(NSString * _Nonnull)type value:(NSString * _Nonnull)value displayText:(NSString * _Nonnull)displayText OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface ReadyRemit (SWIFT_EXTENSION(ReadyRemitSDK))
@end


SWIFT_CLASS("_TtCC13ReadyRemitSDK10ReadyRemit8FontSpec")
@interface FontSpec : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable defaultFamily;)
+ (NSString * _Nullable)defaultFamily SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultFamily:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL dynamicFontsize;)
+ (BOOL)dynamicFontsize SWIFT_WARN_UNUSED_RESULT;
+ (void)setDynamicFontsize:(BOOL)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ReadyRemitApiEnvironment, open) {
  ReadyRemitApiEnvironmentProduction = 0,
  ReadyRemitApiEnvironmentSandbox = 1,
  ReadyRemitApiEnvironmentUat = 2,
};

@class ReadyRemitColorScheme;
@class ReadyRemitFonts;
@class UIColor;
@class UIFont;

SWIFT_CLASS("_TtC13ReadyRemitSDK20ReadyRemitAppearance")
@interface ReadyRemitAppearance : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ReadyRemitAppearance * _Nonnull shared;)
+ (ReadyRemitAppearance * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) ReadyRemitColorScheme * _Nonnull colors;
@property (nonatomic, strong) ReadyRemitFonts * _Nonnull fonts;
- (nonnull instancetype)initWithFonts:(ReadyRemitFonts * _Nonnull)fonts colors:(ReadyRemitColorScheme * _Nonnull)colors OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFonts:(ReadyRemitFonts * _Nonnull)fonts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithColors:(ReadyRemitColorScheme * _Nonnull)colors OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull primaryButtonColor;
@property (nonatomic, strong) UIColor * _Nonnull titleColor;
@property (nonatomic, strong) UIFont * _Nonnull titleFont;
@property (nonatomic, strong) UIFont * _Nonnull pageTitleFont;
@property (nonatomic, strong) UIFont * _Nonnull fieldTitleFont;
@property (nonatomic, strong) UIFont * _Nonnull fieldValueFont;
@property (nonatomic, strong) UIColor * _Nonnull fieldBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull dividerColor;
@property (nonatomic, strong) UIColor * _Nonnull removeColor;
@property (nonatomic, strong) UIColor * _Nonnull buttonColor;
@property (nonatomic, strong) UIColor * _Nonnull disabledColor;
@property (nonatomic, strong) UIFont * _Nonnull disabledFont;
@property (nonatomic, strong) UIColor * _Nonnull highlightedBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull highlightedCapsuleFont;
@property (nonatomic, strong) UIFont * _Nonnull disabledCapsuleFont;
@property (nonatomic, strong) UIColor * _Nonnull currencyDisableColor;
@property (nonatomic, strong) UIFont * _Nonnull currencyDisableFont;
@property (nonatomic, strong) UIColor * _Nonnull transferMoneyColor;
@property (nonatomic, strong) UIFont * _Nonnull transferMoneyFont;
@property (nonatomic, strong) UIFont * _Nonnull navigationFont;
@property (nonatomic, strong) UIFont * _Nonnull navigationCancelFont;
@property (nonatomic, strong) UIColor * _Nonnull navigationColor;
@property (nonatomic, strong) UIColor * _Nonnull navigationCancelColor;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull modalTitleFont;
@property (nonatomic, strong) UIColor * _Nonnull modalTransparentColor;
@property (nonatomic, strong) UIFont * _Nonnull noteFont;
@end


SWIFT_CLASS("_TtC13ReadyRemitSDK21ReadyRemitColorScheme")
@interface ReadyRemitColorScheme : NSObject
@property (nonatomic, strong) UIColor * _Nonnull primaryShade1;
@property (nonatomic, strong) UIColor * _Nonnull primaryShade2;
@property (nonatomic, strong) UIColor * _Nonnull secondaryShade1;
@property (nonatomic, strong) UIColor * _Nonnull secondaryShade2;
@property (nonatomic, strong) UIColor * _Nonnull secondaryShade3;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade1;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade2;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade3;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade4;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryShade5;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColorPrimary;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColorSecondary;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColorTertiary;
@property (nonatomic, strong) UIColor * _Nonnull error;
@property (nonatomic, strong) UIColor * _Nonnull success;
@property (nonatomic, strong) UIColor * _Nonnull controlShade1;
@property (nonatomic, strong) UIColor * _Nonnull controlShade2;
@property (nonatomic, strong) UIColor * _Nonnull controlAccessoryShade1;
@property (nonatomic, strong) UIColor * _Nonnull controlAccessoryShade2;
@property (nonatomic, strong) UIColor * _Nonnull textPrimaryDisabled;
@property (nonatomic, strong) UIColor * _Nonnull textTertiaryDisabled;
@property (nonatomic, strong) UIColor * _Nonnull textQuaternaryDisabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13ReadyRemitSDK18ReadyRemitDelegate_")
@protocol ReadyRemitDelegate
- (void)onAuthTokenRequestWithSuccess:(void (^ _Nonnull)(NSString * _Nonnull))success failure:(void (^ _Nonnull)(void))failure;
- (void)onSubmitTransferWithTransferRequest:(TransferRequest * _Nonnull)transferRequest success:(void (^ _Nonnull)(NSString * _Nonnull))success failure:(void (^ _Nonnull)(NSString * _Nonnull, NSString * _Nonnull))failure;
@optional
- (void)onSDKClose;
@end


SWIFT_CLASS("_TtC13ReadyRemitSDK15ReadyRemitFonts")
@interface ReadyRemitFonts : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ReadyRemitSDK24ReadyRemitObjcOAuthToken")
@interface ReadyRemitObjcOAuthToken : NSObject
- (nonnull instancetype)initWithTokenType:(NSString * _Nonnull)tokenType accessToken:(NSString * _Nonnull)accessToken expiresInSeconds:(NSInteger)expiresInSeconds OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end










#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
